kind: Service
apiVersion: v1
metadata:
  name: xdrienovskym2-openapi-ui
spec:
  selector:
    pod: xdrienovskym2-ambulance-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081
