/*
 * Waiting List Api
 *
 * Ambulance Waiting List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: your_email@stuba.sk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package ambulance_wl

import (
	"github.com/gin-gonic/gin"
)

type AmbulanceConditionsAPI interface {


    // CreateCondition Post /api/waiting-list/:ambulanceId/condition
    // Adds new predefined condition 
     CreateCondition(c *gin.Context)

    // DeleteCondition Delete /api/waiting-list/:ambulanceId/condition/:conditionCode
    // Deletes one predefined condition 
     DeleteCondition(c *gin.Context)

    // GetConditions Get /api/waiting-list/:ambulanceId/condition
    // Provides the list of conditions associated with ambulance 
     GetConditions(c *gin.Context)

    // UpdateConditions Put /api/waiting-list/:ambulanceId/condition
    // Replaces predefined conditions list 
     UpdateConditions(c *gin.Context)

}